# buildspec.yml

version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1" # Update with your region
    AWS_ACCOUNT_ID: "975049886518"  # Update with your AWS account ID
    IMAGE_REPO_NAME: "eks-codebuild" # Update with your ECR repository 


phases:
  install:
    runtime-versions:
#      docker: 18
      nodejs: 14
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
#  post_build:
#    commands:
#      - echo Build completed on `date`
#      - echo Deploying to EKS...
#      - kubectl apply -f k8s/deployment.yaml

#artifacts:
#  files:
#    - '**/*'
#  discard-paths: yes
