apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-nodejs
  template:
    metadata:
      labels:
        app: webapp-nodejs
    spec:
      containers:
      - name: webapp-nodejs
        image: 975049886518.dkr.ecr.us-east-1.amazonaws.com/eks-codebuild:TAG_PLACEHOLDER
        ports:
          - containerPort: 3000
